# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 298c4bffd0a9d52d526e0ed40ba0bba312dc4b6c1db21276dcad53cb7b01ca5726ceec6b1cbcb271d3f7e75b6293344c564bde3f60c4991c5636efabbf33b180

test:
  secret_key_base: c2ccc6fbc37e41e7aafdfc23ce1b161eb0f2598395bcc3b247b73019068385fbf7fb93cf469130e2da6e8f0c120393fc8c9750faf7a0ca78a5d5556cd2e45594

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
